defmodule Ytdarr.Repo.Migrations.AddDownloadStateToVideos do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:videos) do
      add :download_state, :text, null: false, default: "available"
    end
  end

  def down do
    alter table(:videos) do
      remove :download_state
    end
  end
end