defmodule Ytdarr.Repo.Migrations.InitialSettings do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:yt_dlp_param_sets, primary_key: false) do
      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :is_default, :boolean
      add :concurrency, :bigint
      add :rate_limit_kbps, :bigint
      add :extra_args, :text
      add :format, :text
      add :name, :text, null: false
      add :id, :bigserial, null: false, primary_key: true
    end

    create unique_index(:yt_dlp_param_sets, [:name], name: "yt_dlp_param_sets_unique_name_index")

    create table(:quality_profiles, primary_key: false) do
      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :is_default, :boolean
      add :format_selector, :text
      add :allow_hdr, :boolean
      add :preferred_codecs, {:array, :text}, default: []
      add :max_bitrate_kbps, :bigint
      add :max_height, :bigint
      add :name, :text, null: false
      add :id, :bigserial, null: false, primary_key: true
    end

    create unique_index(:quality_profiles, [:name], name: "quality_profiles_unique_name_index")

    create table(:media_root_folders, primary_key: false) do
      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :active, :boolean, null: false
      add :purpose, :text, null: false
      add :path, :text, null: false
      add :id, :bigserial, null: false, primary_key: true
    end

    create unique_index(:media_root_folders, [:path],
             name: "media_root_folders_unique_path_index"
           )

    create table(:app_settings, primary_key: false) do
      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :type, :text, null: false
      add :value, :map, null: false
      add :key, :text, null: false
      add :id, :bigserial, null: false, primary_key: true
    end

    create unique_index(:app_settings, [:key], name: "app_settings_unique_key_index")
  end

  def down do
    drop_if_exists unique_index(:app_settings, [:key], name: "app_settings_unique_key_index")

    drop table(:app_settings)

    drop_if_exists unique_index(:media_root_folders, [:path],
                     name: "media_root_folders_unique_path_index"
                   )

    drop table(:media_root_folders)

    drop_if_exists unique_index(:quality_profiles, [:name],
                     name: "quality_profiles_unique_name_index"
                   )

    drop table(:quality_profiles)

    drop_if_exists unique_index(:yt_dlp_param_sets, [:name],
                     name: "yt_dlp_param_sets_unique_name_index"
                   )

    drop table(:yt_dlp_param_sets)
  end
end