defmodule Ytdarr.Repo.Migrations.InitialSchema do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:yt_dlp_param_sets, primary_key: false) do
      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :is_default, :boolean
      add :concurrency, :bigint
      add :rate_limit_kbps, :bigint
      add :extra_args, :text
      add :format, :text
      add :name, :text, null: false
      add :id, :bigserial, null: false, primary_key: true
    end

    create unique_index(:yt_dlp_param_sets, [:name], name: "yt_dlp_param_sets_unique_name_index")

    create table(:videos, primary_key: false) do
      add :channel_id,
          references(:channels, column: :id, name: "videos_channel_id_fkey", type: :bigint),
          null: false

      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :position_in_uploads, :bigint
      add :discovered_at, :utc_datetime
      add :discovered_from, :text
      add :download_quality, :text
      add :file_size, :bigint
      add :download_path, :text
      add :downloaded_at, :utc_datetime
      add :is_downloaded, :boolean, null: false
      add :thumbnail_url, :text
      add :upload_date, :date
      add :duration, :bigint
      add :description, :text
      add :url, :text, null: false
      add :external_id, :text, null: false
      add :title, :text, null: false
      add :id, :bigserial, null: false, primary_key: true
    end

    create table(:users, primary_key: false) do
      add :confirmed_at, :utc_datetime_usec
      add :hashed_password, :text
      add :email, :citext, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create unique_index(:users, [:email], name: "users_unique_email_index")

    create table(:tokens, primary_key: false) do
      add :updated_at, :utc_datetime_usec, null: false
      add :created_at, :utc_datetime_usec, null: false
      add :extra_data, :map
      add :purpose, :text, null: false
      add :expires_at, :utc_datetime, null: false
      add :subject, :text, null: false
      add :jti, :text, null: false, primary_key: true
    end

    create table(:quality_profiles, primary_key: false) do
      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :is_default, :boolean
      add :format_selector, :text
      add :allow_hdr, :boolean
      add :preferred_codecs, {:array, :text}, default: []
      add :max_bitrate_kbps, :bigint
      add :max_height, :bigint
      add :name, :text, null: false
      add :id, :bigserial, null: false, primary_key: true
    end

    create unique_index(:quality_profiles, [:name], name: "quality_profiles_unique_name_index")

    create table(:playlists, primary_key: false) do
      add :channel_id,
          references(:channels, column: :id, name: "playlists_channel_id_fkey", type: :bigint),
          null: false

      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :download_path, :text
      add :last_checked_at, :utc_datetime
      add :is_monitored_since, :utc_datetime
      add :is_monitored, :boolean, null: false
      add :video_count, :bigint
      add :description, :text
      add :url, :text, null: false
      add :external_id, :text, null: false
      add :name, :text, null: false
      add :id, :bigserial, null: false, primary_key: true
    end

    create table(:playlist_videos, primary_key: false) do
      add :video_id,
          references(:videos, column: :id, name: "playlist_videos_video_id_fkey", type: :bigint),
          primary_key: true,
          null: false

      add :playlist_id,
          references(:playlists,
            column: :id,
            name: "playlist_videos_playlist_id_fkey",
            type: :bigint
          ), primary_key: true, null: false

      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :position, :bigint
      add :id, :bigserial, null: false, primary_key: true
    end

    create unique_index(:playlist_videos, [:playlist_id, :video_id],
             name: "playlist_videos_unique_playlist_video_index"
           )

    create table(:media_root_folders, primary_key: false) do
      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :active, :boolean, null: false
      add :purpose, :text, null: false
      add :path, :text, null: false
      add :id, :bigserial, null: false, primary_key: true
    end

    create unique_index(:media_root_folders, [:path],
             name: "media_root_folders_unique_path_index"
           )

    create table(:channels, primary_key: false) do
      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :generic_video_path, :text
      add :base_path, :text
      add :last_video_published_at, :utc_datetime
      add :last_checked_at, :utc_datetime
      add :is_monitored_since, :utc_datetime
      add :is_monitored, :boolean, null: false
      add :uploads_playlist_id, :text
      add :platform_username, :text
      add :banner_url, :text
      add :avatar_url, :text
      add :platform, :text, null: false
      add :description, :text
      add :url, :text, null: false
      add :external_id, :text, null: false
      add :name, :text, null: false
      add :id, :bigserial, null: false, primary_key: true
    end

    create unique_index(:videos, [:external_id], name: "videos_unique_external_id_index")

    create unique_index(:playlists, [:external_id], name: "playlists_unique_external_id_index")

    create unique_index(:channels, [:external_id], name: "channels_unique_external_id_index")

    create table(:app_settings, primary_key: false) do
      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :type, :text, null: false
      add :value, :map, null: false
      add :key, :text, null: false
      add :id, :bigserial, null: false, primary_key: true
    end

    create unique_index(:app_settings, [:key], name: "app_settings_unique_key_index")
  end

  def down do
    drop_if_exists unique_index(:app_settings, [:key], name: "app_settings_unique_key_index")

    drop table(:app_settings)

    drop_if_exists unique_index(:channels, [:external_id],
                     name: "channels_unique_external_id_index"
                   )

    drop_if_exists unique_index(:playlists, [:external_id],
                     name: "playlists_unique_external_id_index"
                   )

    drop_if_exists unique_index(:videos, [:external_id], name: "videos_unique_external_id_index")

    drop table(:channels)

    drop_if_exists unique_index(:media_root_folders, [:path],
                     name: "media_root_folders_unique_path_index"
                   )

    drop table(:media_root_folders)

    drop_if_exists unique_index(:playlist_videos, [:playlist_id, :video_id],
                     name: "playlist_videos_unique_playlist_video_index"
                   )

    drop constraint(:playlist_videos, "playlist_videos_playlist_id_fkey")

    drop constraint(:playlist_videos, "playlist_videos_video_id_fkey")

    drop table(:playlist_videos)

    drop constraint(:playlists, "playlists_channel_id_fkey")

    drop table(:playlists)

    drop_if_exists unique_index(:quality_profiles, [:name],
                     name: "quality_profiles_unique_name_index"
                   )

    drop table(:quality_profiles)

    drop table(:tokens)

    drop_if_exists unique_index(:users, [:email], name: "users_unique_email_index")

    drop table(:users)

    drop constraint(:videos, "videos_channel_id_fkey")

    drop table(:videos)

    drop_if_exists unique_index(:yt_dlp_param_sets, [:name],
                     name: "yt_dlp_param_sets_unique_name_index"
                   )

    drop table(:yt_dlp_param_sets)
  end
end
