defmodule Ytdarr.Repo.Migrations.AddVideoBlocklist do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:videos) do
      add :is_blocklisted, :boolean, null: false, default: false
    end
  end

  def down do
    alter table(:videos) do
      remove :is_blocklisted
    end
  end
end
