defmodule Ytdarr.Repo.Migrations.MigrateResources1 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:channels, primary_key: false) do
      add :id, :bigserial, null: false, primary_key: true
      add :name, :text, null: false
      add :external_id, :text, null: false
      add :url, :text, null: false
      add :description, :text
      add :platform, :text, null: false
      add :avatar_url, :text
      add :banner_url, :text
      add :platform_username, :text
      add :is_monitored, :boolean, null: false, default: false
      add :is_monitored_since, :utc_datetime
      add :last_checked_at, :utc_datetime
      add :base_path, :text
      add :generic_video_path, :text
      add :inserted_at, :utc_datetime_usec, null: false
      add :updated_at, :utc_datetime_usec, null: false
    end

    create unique_index(:channels, [:external_id], name: "channels_unique_external_id_index")

    create table(:videos, primary_key: false) do
      add :id, :bigserial, null: false, primary_key: true
      add :title, :text, null: false
      add :external_id, :text, null: false
      add :url, :text, null: false
      add :description, :text
      add :duration, :bigint
      add :upload_date, :date
      add :thumbnail_url, :text
      add :is_downloaded, :boolean, null: false, default: false
      add :downloaded_at, :utc_datetime
      add :download_path, :text
      add :file_size, :bigint
      add :download_quality, :text
      add :discovered_from, :text
      add :discovered_at, :utc_datetime
      add :position_in_uploads, :bigint
      add :inserted_at, :utc_datetime_usec, null: false
      add :updated_at, :utc_datetime_usec, null: false

      add :channel_id,
          references(:channels, column: :id, name: "videos_channel_id_fkey", type: :bigint, on_delete: :delete_all),
          null: false
    end

    create unique_index(:videos, [:external_id], name: "videos_unique_external_id_index")

    create table(:playlists, primary_key: false) do
      add :id, :bigserial, null: false, primary_key: true
      add :name, :text, null: false
      add :external_id, :text, null: false
      add :url, :text, null: false
      add :description, :text
      add :video_count, :bigint
      add :is_monitored, :boolean, null: false, default: false
      add :is_monitored_since, :utc_datetime
      add :last_checked_at, :utc_datetime
      add :download_path, :text
      add :inserted_at, :utc_datetime_usec, null: false
      add :updated_at, :utc_datetime_usec, null: false

      add :channel_id,
          references(:channels, column: :id, name: "playlists_channel_id_fkey", type: :bigint, on_delete: :delete_all),
          null: false
    end

    create unique_index(:playlists, [:external_id], name: "playlists_unique_external_id_index")

    create table(:playlist_videos, primary_key: false) do
      add :id, :bigserial, null: false, primary_key: true
      add :position, :bigint
      add :inserted_at, :utc_datetime_usec, null: false
      add :updated_at, :utc_datetime_usec, null: false

      add :playlist_id,
          references(:playlists, column: :id, name: "playlist_videos_playlist_id_fkey", type: :bigint, on_delete: :delete_all),
          null: false

      add :video_id,
          references(:videos, column: :id, name: "playlist_videos_video_id_fkey", type: :bigint, on_delete: :delete_all),
          null: false
    end

    create unique_index(:playlist_videos, [:playlist_id, :video_id],
             name: "playlist_videos_unique_playlist_video_index"
           )
  end

  def down do
    drop_if_exists unique_index(:playlist_videos, [:playlist_id, :video_id],
                     name: "playlist_videos_unique_playlist_video_index"
                   )

    drop table(:playlist_videos)

    drop_if_exists unique_index(:playlists, [:external_id],
                     name: "playlists_unique_external_id_index"
                   )

    drop table(:playlists)

    drop_if_exists unique_index(:videos, [:external_id], name: "videos_unique_external_id_index")

    drop table(:videos)

    drop_if_exists unique_index(:channels, [:external_id],
                     name: "channels_unique_external_id_index"
                   )

    drop table(:channels)
  end
end
