defmodule Ytdarr.Repo.Migrations.MigrateResources2 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:channels) do
      add :uploads_playlist_id, :text
    end
  end

  def down do
    alter table(:channels) do
      remove :uploads_playlist_id
    end
  end
end