defmodule Ytdarr.Repo.Migrations.AddVideoImportState do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:videos) do
      add :import_error, :text
      add :import_job_id, :bigint
      add :import_manifest, :map
      add :import_recovery, :map, null: false, default: %{"mode" => nil, "entries" => []}
    end
  end

  def down do
    alter table(:videos) do
      remove :import_recovery
      remove :import_manifest
      remove :import_job_id
      remove :import_error
    end
  end
end
